apiVersion: v1
kind: Service

metadata:
  name: sparta-svc
  namespace: default # can name them in different namespaces within the same cluster
spec:
  ports:
    - nodePort: 30003 # range is 30000-32768
      port: 80
      targetPort: 3000
  selector:
    app: sparta # connects this service to the nginx deployment
  type: NodePort # type of service. Also use LoadBalancer - for local use cluster IP